image: node:latest
stages:
   - test
   - build
   - deploy

test-project:
   stage: test
   script:
        - yarn install
        - yarn test
        
build-project:
   stage: build
   script:
        - yarn install
        - yarn build 
   artifacts:
      paths:
        - build/
netlify:
    stage: deploy
    script:
         - npm install -g netlify-cli
         - netlify deploy --dir=build --prod